import type { Project, Shot, Version } from './api-client';

export const mockProjects: Project[] = [
  {
    id: 1,
    name: 'The Martian Chronicles',
    type: 'story',
    resolution: { width: 1920, height: 1080 },
    fps: 24,
    lock_character: false,
    lock_style: false,
    lock_world: false,
    lock_key_object: false,
    updated_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    cover_url: 'https://placehold.co/600x400/1a1a1a/FFF?text=Martian',
  },
  {
    id: 2,
    name: 'Cyberpunk Short',
    type: 'animation',
    resolution: { width: 1920, height: 1080 },
    fps: 24,
    lock_character: true,
    lock_style: true,
    lock_world: false,
    lock_key_object: false,
    updated_at: new Date(Date.now() - 86400000).toISOString(),
    created_at: new Date(Date.now() - 86400000).toISOString(),
    cover_url: 'https://placehold.co/600x400/2a2a2a/FFF?text=Cyberpunk',
  },
];

export const mockShots: Shot[] = [
  {
    id: 1,
    scene_id: 1,
    order: 1,
    shot_type: 'Close Up',
    camera_move: 'Static',
    duration: 5.0,
    composition: 'Rule of Thirds',
    lens: '35mm',
    story_desc: 'The beginning of the journey.',
    visual_desc: 'Red sand blowing in the wind.',
    prompt: 'A vast Martian landscape with red sand dunes.',
    negative_prompt: null,
    asset_refs: [],
    status: 'completed',
    updated_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: 2,
    scene_id: 1,
    order: 2,
    shot_type: 'Wide Shot',
    camera_move: 'Pan Left',
    duration: 8.0,
    composition: 'Centered',
    lens: '24mm',
    story_desc: 'Astronaut explores.',
    visual_desc: 'Low angle shot of the astronaut.',
    prompt: 'A astronaut walking on the surface of Mars.',
    negative_prompt: null,
    asset_refs: [],
    status: 'completed',
    updated_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },
];

export const mockVersions: Version[] = [
  {
    id: 1,
    shot_id: 1,
    type: 'image',
    url: 'https://placehold.co/600x400/8B0000/FFF?text=Martian+Landscape',
    params: {},
    is_primary: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 2,
    shot_id: 2,
    type: 'image',
    url: 'https://placehold.co/600x400/4B0082/FFF?text=Astronaut+on+Mars',
    params: {},
    is_primary: true,
    created_at: new Date().toISOString(),
  },
];
